### ISSUE TITLE
Update GitHub to CRAN version

### ISSUE THREAD

**Issue by zeileis** [gamlss-dev/gamlss.data#1]
Mikis @mstasinopoulos, the CRAN version of `gamlss.data` is 6.0-2 from 2021 but the GitHub repository is at version 4.2-6 from 2013. The latter should be updated to be in sync with the CRAN version so that we can make future CRAN releases from the GitHub version.

**Comment by mstasinopoulos** [comment]
Thanks for point out to me this.

 I  will do that when I solve the problem of reseting all by git connection in R-studio

Do you know  how I can reset in R-studio the git from say 


https://github.com/mstasinopoulos/GAMLSS-original.git

To 

https://github.com/gamlss-dev/gamlss.git


Thanks

Mikis

**Comment by zeileis** [comment]
**If you haven't got any more local changes or untracked additions**, then the easiest solution is to do a new `git clone` of the transferred repository. This will also change the name of the main branch from `master` to `main` (which I did for consistency for all repositories, was inconsistent before).

-----

**If you have local untracked changes/modifications** that you want to preserve then the following should work:

```
git remote set-url origin NEW_URL
```

where the `NEW_URL` has to be set accordingly for all the repositories.

To switch from the `master` to the `main` branch you additionally need to do:

```
git branch -m master main
git fetch origin
git branch -u origin/main main
git remote set-head origin -a
```

**Comment by zeileis** [comment]
Any progress here, Mikis? Is there anyone who also has access to the updated version of the repository?

Otherwise, you could possibly just copy all of the current CRAN files as a new revision into this repository.

**Comment by zeileis** [comment]
This issue was also addressed by the PR https://github.com/gamlss-dev/gamlss.data/pull/2 merged today. Thanks, Mikis @mstasinopoulos !

The `main` branch now has the CRAN version plus a few small improvements in `DESCRIPTION` and a `NEWS.md` file.

Please just make sure that in your local copy you also switch to the `main` branch now.
